services:
  - type: web
    name: telegram-signal-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7709373432:AAFF5Myus4UnvjCXwzW_wu2JIh7iWnHzX6k
